### ISSUE TITLE
BUG: classname referenced before assignment when launching jobflow-based fireworks

### ISSUE THREAD

**Issue by arosen93** [materialsproject/jobflow#72]
**Describe the bug**
When using Jobflow 0.1.6 and Fireworks 1.9.8, I am able to convert a Jobflow flow into a Fireworks workflow and put it into my launchpad, but I am unable to launch the firework if it contains @job-decorated functions, as monty returns an error of `UnboundLocalError: local variable 'classname' referenced before assignment` (see below). This happens even for the tutorial Jobflow example.

The issue is the following dictionary in the Firework spec: `{'@module': '__main__', '@callable': 'add', '@bound': None}`. It has no `@class` attribute, and the `classname` variable never gets defined [here](https://github.com/materialsvirtuallab/monty/blob/cd4bb8c185a303e90a332047102d9119d957fa31/monty/json.py#L364-L387).

I have opened a monty [PR here](https://github.com/materialsvirtuallab/monty/pull/335). Since this seems to be a monty issue, feel free to close this if you wish. Having it documented here will be nice either way in case anyone stumbled upon it before the monty PR gets merged. If you have any alternate suggestions, please let me know.

```python
from jobflow import job, Flow
from fireworks import LaunchPad
from jobflow.managers.fireworks import flow_to_workflow

@job
def add(a, b):
    return a + b

add_first = add(1, 5)
add_second = add(add_first.output, 5)
flow = Flow([add_first, add_second])
wf = flow_to_workflow(flow)
lpad = LaunchPad.auto_load()
lpad.add_wf(wf)
```
```bash
> qlaunch singleshot
Traceback (most recent call last):
  File "/global/homes/r/rosen/software/miniconda/envs/cms/bin/qlaunch", line 8, in <module>
    sys.exit(qlaunch())
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/scripts/qlaunch_run.py", line 264, in qlaunch
    do_launch(args)
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/scripts/qlaunch_run.py", line 77, in do_launch
    launch_rocket_to_queue(
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/queue/queue_launcher.py", line 91, in launch_rocket_to_queue
    if fill_mode or launchpad.run_exists(fworker):
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/core/launchpad.py", line 903, in run_exists
    return bool(self._get_a_fw_to_run(query=q, checkout=False))
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/core/launchpad.py", line 1180, in _get_a_fw_to_run
    m_fw = self.get_fw_by_id(m_fw["fw_id"])
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/core/launchpad.py", line 528, in get_fw_by_id
    return Firework.from_dict(self.get_fw_dict_by_id(fw_id))
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/utilities/fw_serializers.py", line 160, in _decorator
    new_args[0] = {k: _recursive_load(v) for k, v in args[0].items()}
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/utilities/fw_serializers.py", line 160, in <dictcomp>
    new_args[0] = {k: _recursive_load(v) for k, v in args[0].items()}
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/utilities/fw_serializers.py", line 121, in _recursive_load
    return {k: _recursive_load(v) for k, v in obj.items()}
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/utilities/fw_serializers.py", line 121, in <dictcomp>
    return {k: _recursive_load(v) for k, v in obj.items()}
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/utilities/fw_serializers.py", line 124, in _recursive_load
    return [_recursive_load(v) for v in obj]
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/utilities/fw_serializers.py", line 124, in <listcomp>
    return [_recursive_load(v) for v in obj]
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/utilities/fw_serializers.py", line 116, in _recursive_load
    return load_object(obj)
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/utilities/fw_serializers.py", line 338, in load_object
    return cls_.from_dict(obj_dict)
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/utilities/fw_serializers.py", line 160, in _decorator
    new_args[0] = {k: _recursive_load(v) for k, v in args[0].items()}
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/utilities/fw_serializers.py", line 160, in <dictcomp>
    new_args[0] = {k: _recursive_load(v) for k, v in args[0].items()}
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/fireworks/utilities/fw_serializers.py", line 119, in _recursive_load
    return json.loads(json.dumps(obj), cls=MontyDecoder)
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/monty/json.py", line 438, in decode
    return self.process_decoded(d)
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/monty/json.py", line 407, in process_decoded
    return cls_.from_dict(data)
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/monty/json.py", line 179, in from_dict
    decoded = {k: MontyDecoder().process_decoded(v) for k, v in d.items() if not k.startswith("@")}
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/monty/json.py", line 179, in <dictcomp>
    decoded = {k: MontyDecoder().process_decoded(v) for k, v in d.items() if not k.startswith("@")}
  File "/global/homes/r/rosen/software/miniconda/envs/cms/lib/python3.8/site-packages/monty/json.py", line 402, in process_decoded
    mod = __import__(modname, globals(), locals(), [classname], 0)
UnboundLocalError: local variable 'classname' referenced before assignment
```

In case it helps, here is the `READY` firework. Pay special attention to the `function` dictionary.
```
{
"_id": null,
"archived_launches": [ ],
"created_on": "2022-01-01T01:27:49.668777",
"fw_id": 309,
"launches": [ ],
"name": "add",
-"spec": {
"_add_launchpad_and_fw_id": true,
-"_tasks": [
-{
"_fw_name": "{{jobflow.managers.fireworks.JobFiretask}}",
-"job": {
"@class": "Job",
"@module": "jobflow.core.job",
"@version": "",
-"config": {
"@class": "JobConfig",
"@module": "jobflow.core.job",
"@version": "",
"expose_store": false,
"manager_config": { },
"on_missing_references": "error",
"pass_manager_config": true,
"resolve_references": true
},
-"function": {
"@bound": null,
"@callable": "add",
"@module": "__main__"
},
-"function_args": [
1,
5
],
"function_kwargs": { },
"host": "9bcbc769-f644-4ef9-9260-99ed9c93367d",
"index": 1,
"metadata": { },
"name": "add",
"output_schema": null,
"uuid": "05b233dc-231b-4071-a791-af6702059cb5"
},
"store": null
}
]
},
"state": "READY",
"updated_on": "2022-01-01T01:27:49.675906"
}
```

**Comment by utf** [comment]
Ah I think this must be because the function is defined in `__main__` rather than a module. Thanks for catching.

**Comment by utf** [comment]
Actually, I'm not sure this could ever work on Fireworks side, unless you're running fireworks in the same script in which the job was made, as it won't have access to the same functions defined in `__main__`.

In general, for objects to be used in Fireworks, they need to be defined in a module somewhere so that they can be imported.

**Comment by arosen93** [comment]
@utf: Ah, thanks for your input. I got the job to submit to the queue but naively didn't check the output.

That's a bummer. I've been making a bunch of jobflow flows (tested by running locally, which of course worked fine) using @job-decorated functions. I was hoping the switch to fireworks would be smooth but perhaps not. I guess I'll need to rethink how I'm structuring things.

**Comment by utf** [comment]
The easiest thing is just to have a python library of your functions which is installed both locally and on the remote machine. Hopefully that shouldn't be much trouble.

**Comment by arosen93** [comment]
Agreed, that seems to be the simplest solution. Thanks again!

Just for context, this is all coming up because I've been trying to enable Atomate2-style workflows centered around ASE and for it to play nicely with Fireworks. Jobflow seemed like a great way to do that. You can see some an initial attempt here: https://github.com/arosen93/htase. At least for VASP, I know it's mostly rehashing a lot of things, but it was a useful exercise. I have some more complex ASE-based flows now (not shown) that I'm planning to run with Fireworks after getting them up and running locally.
